### ISSUE TITLE
CSS isn't a programming language but..

### ISSUE THREAD

**Issue by LukyVj** [ad-si/RosettaGit#29]
You could easily make an "Hello world" in CSS using pseudo-element and a pseudo class ( :before/:after ) using the "content" property. Like so:

```css

.element:after { 
  content: "Hello world"
}

```

**Comment by RemasteredArch** [comment]
Using `body` as the selector would make it work without needing to add HTML.  
```css
body::after {
  content: 'Hello World!'
}
```
